name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      -
        name: build and push on ECR
        uses: ${{ github.repository }}@v4.1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: ${github.repository}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.ref_name }}
          create_repo: true
          image_scanning_configuration: true
          set_repo_policy: true
          repo_policy_file: repo-policy.json
          kms_arn: ${{ secrets.ECR_KMS_ID }}
